/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `food` (
  `FOOD_NO` int(11) NOT NULL AUTO_INCREMENT COMMENT '음식번호',
  `FOOD_NAME` varchar(50) NOT NULL DEFAULT '0' COMMENT '메뉴 이름',
  `FOOD_CAL` int(11) DEFAULT '0' COMMENT '칼로리',
  `FOOD_KIND` int(11) NOT NULL DEFAULT '0' COMMENT '메뉴 구분 (10: 밥/ 20: 국/ 30: 면 40: 반찬 50:후식)',
  PRIMARY KEY (`FOOD_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='음식';

DELETE FROM `food`;
/*!40000 ALTER TABLE `food` DISABLE KEYS */;
/*!40000 ALTER TABLE `food` ENABLE KEYS */;

CREATE TABLE IF NOT EXISTS `food_set` (
  `MENU_NO` int(11) NOT NULL COMMENT '식단번호 (FK)',
  `FOOD_NO` int(11) NOT NULL COMMENT '음식번호 (FK)',
  PRIMARY KEY (`MENU_NO`,`FOOD_NO`),
  KEY `FK_food_set_food` (`FOOD_NO`),
  CONSTRAINT `FK_food_set_food` FOREIGN KEY (`FOOD_NO`) REFERENCES `food` (`FOOD_NO`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_food_set_menu` FOREIGN KEY (`MENU_NO`) REFERENCES `menu` (`MENU_NO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='음식 세트';

DELETE FROM `food_set`;
/*!40000 ALTER TABLE `food_set` DISABLE KEYS */;
/*!40000 ALTER TABLE `food_set` ENABLE KEYS */;

CREATE TABLE IF NOT EXISTS `log` (
  `USR_NO` int(11) NOT NULL COMMENT '회원번호 (FK)',
  `MENU_NO` int(11) NOT NULL COMMENT '식단번호 (FK)',
  PRIMARY KEY (`USR_NO`,`MENU_NO`),
  KEY `FK_log_menu` (`MENU_NO`),
  CONSTRAINT `FK_log_menu` FOREIGN KEY (`MENU_NO`) REFERENCES `menu` (`MENU_NO`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_log_usrs` FOREIGN KEY (`USR_NO`) REFERENCES `usrs` (`USR_NO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='식사 로그';

DELETE FROM `log`;
/*!40000 ALTER TABLE `log` DISABLE KEYS */;
/*!40000 ALTER TABLE `log` ENABLE KEYS */;

CREATE TABLE IF NOT EXISTS `menu` (
  `MENU_NO` int(11) NOT NULL AUTO_INCREMENT COMMENT '식단번호',
  `MENU_DT` date NOT NULL COMMENT '날짜',
  `MENU_KIND` int(11) NOT NULL COMMENT '구분 10: 아침, 20: 점심, 30: 저녁',
  `MENU_FILE_NAME` varchar(50) NOT NULL COMMENT '이미지 파일명',
  PRIMARY KEY (`MENU_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='식단';

DELETE FROM `menu`;
/*!40000 ALTER TABLE `menu` DISABLE KEYS */;
/*!40000 ALTER TABLE `menu` ENABLE KEYS */;

CREATE TABLE IF NOT EXISTS `usrs` (
  `USR_NO` int(11) NOT NULL AUTO_INCREMENT COMMENT '회원번호',
  `USR_ID` varchar(50) NOT NULL COMMENT '아이디 (이메일)',
  `USR_NM` varchar(50) NOT NULL COMMENT '이름',
  `USR_PWD` varchar(50) NOT NULL COMMENT '비밀번호',
  `USR_PM` int(11) NOT NULL COMMENT '권한 10: 관리자, 20: 이용자',
  `JOIN_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  PRIMARY KEY (`USR_NO`),
  UNIQUE KEY `USR_ID` (`USR_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8 COMMENT='회원';

DELETE FROM `usrs`;
/*!40000 ALTER TABLE `usrs` DISABLE KEYS */;
INSERT INTO `usrs` (`USR_NO`, `USR_ID`, `USR_NM`, `USR_PWD`, `USR_PM`, `JOIN_DT`) VALUES
	(1, 'kwongusgn@gmail.com', '권현후', 'test', 20, '2017-05-27 11:34:44'),
	(2, 'csj21300@naver.com', '최성진', 'test', 20, '2017-05-27 11:35:56'),
	(3, 'vaporize93@gmail.com', '김준수', 'test', 20, '2017-05-27 11:36:15'),
	(4, 'team.kimkongko@gmail.com', '관리자', 'test', 10, '2017-05-27 11:37:07');
/*!40000 ALTER TABLE `usrs` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
